name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv,logs,plugins
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv,logs,plugins
      continue-on-error: true
    
    - name: Test with pytest
      run: |
        python -m pytest tests/ -v
      continue-on-error: true
    
    - name: Check ETL modules
      run: |
        python -c "
        import sys, os
        sys.path.append('etl')
        try:
            print('Testing ETL module imports...')
            import extract
            import transform  
            import load
            print('✅ All ETL modules imported successfully')
        except Exception as e:
            print(f'⚠️  Import warning: {e}')
        "
      continue-on-error: true
